
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Four2OneMux(

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg[1:0] S;
reg[1:0] U;
reg[1:0] V;
reg[1:0] W;
reg[1:0] X;
reg[1:0] M;


//=======================================================
//  Structural coding
//=======================================================

always@(*)
begin

	S=SW[9:8];
	
	U=SW[1:0];
	V=SW[3:2];
	W=SW[5:4];
	X=SW[7:6];
	
	case(S)
		0: M=U;
		1: M=V;
		2: M=W;
		3: M=X;
		default: M=U;
	endcase

end
	
assign LEDR[1:0] = M;
assign LEDR[9:8] = SW[9:8];


endmodule
