
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SevenSeg_Basic(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg[1:0] c;
reg[7:0] data; 

//=======================================================
//  Structural coding
//=======================================================

always@(*)
begin
	c = SW[1:0];
	case(c)
		0: data=8'b10100001;
		1: data=8'b10000110;
		2: data=8'b11111001;
		default: data=8'b11000000;
	
	endcase
	
end

assign HEX0 = data;

endmodule
