
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SevenSeg_Part2(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg[1:0] c;
reg[7:0] d = 8'b10100001;
reg[7:0] e = 8'b10000110;
reg[7:0] one = 8'b11111001;
reg[7:0] zero = 8'b11000000;
reg[7:0] null = 8'b11111111;
reg[47:0] hex_data;

//=======================================================
//  Structural coding
//=======================================================

always@(*)
begin
	
	c = SW[9:7];
	
	case(c)
	
		0: hex_data={null,null,d,e,one,zero};
		1: hex_data={null,d,e,one,zero,null};
		2: hex_data={d,e,one,zero,null,null};
		3: hex_data={e,one,zero,null,null,d};
		4: hex_data={one,zero,null,null,d,e};
		default: hex_data={zero,null,null,d,e,one};
	
	endcase
	

end

assign HEX5 = hex_data[47:40];
assign HEX4 = hex_data[39:32];
assign HEX3 = hex_data[31:24];
assign HEX2 = hex_data[23:16];
assign HEX1 = hex_data[25:8];
assign HEX0 = hex_data[7:0];
	

endmodule
